import { profile } from "console";
import { Phone, Subtitles } from "lucide-react";
import { date, record } from "zod/v4";
import ReviewModal from "./components/ReviewModal";
import { title } from "process";
import AddCar from "./shop/cars/add/page";
import { write } from "fs";

export const texts = {
  th: {
    LanguageSwitcher: {
      thai: "ภาษาไทย",
      english: "English"
    },

    Login: {
      sub:'เข้าสู่ระบบล้มเหลว โปรดตรวจสอบชื่อผู้ใช้และรหัสผ่าน',
      title: "เข้าสู่ระบบ",
      email:"อีเมล",
      username: "ชื่อผู้ใช้",
      password: "รหัสผ่าน",
      Phone:"เบอร์โทรศัพท์",
      confirmpassword: "ยืนยันรหัสผ่าน",
      role: "บทบาท",
      Chooserole: "เลือกบทบาท",
      customer: "ลูกค้า",
      address:"ที่อยู่",
      shop: "ร้าน",
      Reservewhen:"จองเมื่อ",
      shopname: "ชื่อร้านค้า",
      promptpay: "หมายเลขพร้อมเพย์",
      rememberMe: "จดจำฉัน",
      forgotPassword: "ลืมรหัสผ่าน?",
      error:"กรุณากรอกให้ครบถ้วน",
      submit: "เข้าสู่ระบบ",
      submitting: "กำลังดำเนินการ...",
      noAccount: "ยังไม่มีบัญชีผู้ใช้?",
      haveAccount: "มีบัญชีผู้ใช้อยู่แล้ว",
      register: "ลงทะเบียน",
      successRegistered: "ลงทะเบียนสำเร็จ กรุณาเข้าสู่ระบบ",
      loginFailedGeneric: "เข้าสู่ระบบล้มเหลว โปรดตรวจสอบชื่อผู้ใช้และรหัสผ่าน",
      errorDuringLogin: "เกิดข้อผิดพลาดในการเข้าสู่ระบบ",
      validation: {
        usernameRequired: "กรุณากรอกชื่อผู้ใช้",
        passwordRequired: "กรุณากรอกรหัสผ่าน",
      }
    },
    popular:{
    exit:'กลับหน้าหลัก',
    summary:'สรุปรายรับ',
    income:'รายรับรายวัน',
    total:'รายรับทั้งหมด',
    rental:'การเช่าทั้งหมด',
    money:'แนวโน้มรายรับรายเดือน (12 เดือนย้อนหลัง)',
    revenue :'รายรับ',
    top:'5 รถยอดนิยม (ตามจำนวนครั้งที่เช่า)',
    all:'อันดับรถทั้งหมด',
    rating: ' อันดับ',
    license:'ป้ายทะเบียน',
    type:'ประเภท',
    gear:'เกียร์',
    seat:'ที่นั่ง',
    status:'สถานะ',
    available:'ว่าง',
    noavai:'ไม่ว่าง',
    Renting:'กำลังเช่า',
    day:'ต่อวัน',
    time:'ครั้ง',
    review:'รีวิว',
    sum:'สรุปสถิติรถยอดนิยม',
    tr:'ครั้งที่เช่ารวม',
    score:'คะแนนเฉลี่ยรวม',
    reviewt:'รีวิวทั้งหมด',
    yu:'ราคาเฉลี่ย/วัน',
    vv:'จำนวนครั้งที่เช่า',
    },

     blaklist:{
      title:'ระบบจัดการรายชื่อผู้ใช้ที่ถูกระงับ',
      subtitle:'จัดการและควบคุมการเข้าถึงของผู้ใช้งาน',
      other: "อื่นๆ (โปรดระบุ)",
      pleaseFillOther: "โปรดระบุเหตุผลในช่อง 'อื่นๆ'",
      emai:'ค้นหาด้วยชื่อผู้ใช้งานหรืออีเมล',
      search:'ค้นหา',
      label:'เลือกเหตุผลในการระงับ',
      a:'ดัดแปลงรถ โดยไม่อนุญาต',
      b:'คืนรถเกินกำหนด',
      c:'ใช้รถผิดวัตถุประสงค์',
      d:'มีใบสั่งย้อนหลัง',
      e:'อื่นๆ (โปรดระบุ)',
      f:'โปรดระบุเหตุผล',
      listname:'รายชื่อผู้ใช้ที่ถูกระงับ',
      list:'รายการ',
      no:'ไม่มีผู้ใช้ในรายชื่อระงับ',
      notitle:'ผู้ใช้ทั้งหมดสามารถเข้าใช้งานได้ปกติ',
      results:'ผลการค้นหา',
      add:'เพิ่มเข้ารายชื่อระงับ',
      cancel:'ยกเลิกการระงับ',
      date:' วันที่เพิ่ม',
      reason:'เหตุผล',
    },

    

    Home: {
      title: "ยินดีต้อนรับ",
      image:'จัดการรูปภาพ',
      submit: "เข้าสู่ระบบ",
      submittwo: "ลงทะเบียน",
      head: "ระบบบริการเช่ารถ สะดวก รวดเร็ว ครบจบที่เดียว",
      Dashboard:"แดชบอร์ด",
    },
    Addcar: {
      brand:'ยี่ห้อ',
      title:'เพิ่มรถใหม่',
      model:'รุ่น',
      year:'ปี',
      Carregistration:'ทะเบียนรถ',
      type:'ประเภทรถ',
      gear:'เกียร์',
      fuel:'เชื้อเพลิง',
      seats:'จำนวนที่นั่ง',
      color:'สี',
      price:'ราคาเช่าต่อวัน (บาท)',
      Insurance:'ค่าประกัน (บาท)',
      details:'รายละเอียดเพิ่มเติม',
      cancel:'ยกเลิก',
      AddCar:'เพิ่มรถยนต์',
      Sedan:'รถเก๋ง',
      SUV:'รถ SUV',
      hatchback:'รถแฮทช์แบ็ค',
      pickup:'รถกระบะ',
      van:'รถตู้',
      luxury:'รถหรู',
      motorbike:'มอเตอร์ไซค์',
      automatic:'อัตโนมัติ',
      manual:'ธรรมดา',
      gasoline:'น้ำมันเบนซิน',
      diesel:'น้ำมันดีเซล',
      hybrid:'ไฮบริด',
      electric:'ไฟฟ้า',
      seat:'ที่นั่ง',
      money:'0 (ไม่บังคับ)',

    },
    editcar: {
      brand:'ยี่ห้อ',
      title:'แก้ไขข้อมูลรถ',
      model:'รุ่น',
      year:'ปี',
      car:'ทะเบียนรถ',
      type:'ประเภทรถ',
      gear:'เกียร์',
      fuel:'เชื้อเพลิง',
      seats:'จำนวนที่นั่ง',
      color:'สี',
      price:'ราคาเช่าต่อวัน (บาท)',
      details:'รายละเอียดเพิ่มเติม',
      cancel:'ยกเลิก',
      AddCar:'บันทึกการเปลี่ยนแปลง',
      Sedan:'รถเก๋ง',
      SUV:'รถ SUV',
      hatchback:'รถแฮทช์แบ็ค',
      pickup:'รถกระบะ',
      van:'รถตู้',
      luxury:'รถหรู',
      motorbike:'มอเตอร์ไซค์',
      automatic:'อัตโนมัติ',
      manual:'ธรรมดา',
      gasoline:'น้ำมันเบนซิน',
      diesel:'น้ำมันดีเซล',
      hybrid:'ไฮบริด',
      electric:'ไฟฟ้า',
      t:'สถานะรถ',
      status:'ว่าง',
      sstatus:'ถูกเช่า',
      ssstatus:'อยู่ระหว่างการซ่อมบำรุง',
      sssstatus:'ปิดการให้บริการ',
    },

    editimages:{
      edit:'จัดการรูปภาพ',
      new:'อัปโหลดรูปภาพใหม่',
      click:'คลิกเพื่อเลือกไฟล์',
      a:'PNG, JPG, WEBP ขนาดไม่เกิน 5MB',
      b:'เสร็จสิ้น',
    },

    Policy: {
      title: 'จัดการนโยบายร้านค้า',
      subtitle: 'เพิ่ม/แก้ไข/ลบนโยบายที่จะโชว์ให้ลูกค้าเห็นในหน้าร้านของคุณ',
      loading: 'กำลังโหลดนโยบาย...',
      editTitle: 'แก้ไขนโยบาย',
      createTitle: 'สร้างนโยบาย',
      previewTitle: 'ตัวอย่างนโยบาย',
      noPolicy: 'ยังไม่มีนโยบาย โปรดกด “แก้ไข” เพื่อสร้าง',
      noPolicyText: 'ยังไม่มีข้อความ',
      labels: {
        policyText: 'ข้อความนโยบาย (จะแสดงต่อผู้ใช้)',
        preview: 'ตัวอย่างที่ลูกค้าจะเห็น',
      },
      buttons: {
        edit: 'แก้ไข',
        create: 'สร้างนโยบาย',
        delete: 'ลบนโยบาย',
        deleting: 'กำลังลบ...',
        save: 'บันทึกนโยบาย',
        saving: 'กำลังบันทึก...',
        showPreview: 'แสดงตัวอย่าง',
        hidePreview: 'ซ่อนตัวอย่าง',
      },
      errors: {
        fetchFailed: 'ไม่สามารถโหลดนโยบายได้',
        emptyPolicy: 'กรุณากรอกข้อความนโยบาย',
        saveFailed: 'บันทึกนโยบายไม่สำเร็จ',
        deleteFailed: 'ลบนโยบายไม่สำเร็จ',
      },
      success: {
        created: 'สร้างนโยบายสำเร็จ',
        updated: 'แก้นโยบายสำเร็จ',
        deleted: 'ลบนโยบายเรียบร้อย',
      },
      deleteConfirm: {
        title: 'ยืนยันการลบนโยบาย',
        message: 'เมื่อลบแล้วลูกค้าจะไม่เห็นนโยบายบนหน้าร้านของคุณ ต้องการดำเนินการต่อหรือไม่?',
      },
    },
  

    carsatana:{
      car:'จัดการสถานะรถ',
      a:'เลือกสถานะที่ต้องการเปลี่ยน',
      status:'ว่าง',
      sstatus:'ถูกเช่า',
      ssstatus:'อยู่ระหว่างการซ่อมบำรุง',
      sssstatus:'ปิดการให้บริการ',
       cc:'ยกเลิก',
      pp:'เปลี่ยนสถานะ',
    },

    profile:{
      title: "โปรไฟล์ของฉัน",
      subtitle: "จัดการข้อมูลส่วนตัวและดูสถิติการใช้งาน",
      header:"ข้อมูลส่วนตัว",
      date:"สมาชิกตั้งแต่",
      edit:"แก้ไข",
      statistics:"สถิติการใช้งาน",
      all:"การจองทั้งหมด",
     
      use:"กำลังใช้งาน",
     
      finish:"เสร็จสิ้น",
      ff:'อัปเดตโปรไฟล์เรียบร้อยแล้ว',
    },
    
     shopprofile:{
      title: "โปรไฟล์ร้านค้า",
      subtitle: "จัดการข้อมูลส่วนตัวและร้านค้าของคุณ",
      edit:'แก้ไขข้อมูล',
      header:"ชื่อผู้ใช้",
      subheader:"ชื่อร้านค้า",
      pp:"หมายเลขพร้อมเพย์",
      tel:"หมายเลขโทรศัพท์",
      address:"ที่อยู่",
      date:"สมาชิกเมื่อ",
      email:"อีเมล",
      shop:"บทบาท",
      ee:"ร้านค้า",
      back:"ย้อนกลับ",
      ff:'อัปเดตโปรไฟล์เรียบร้อยแล้ว',
      cc:'ยกเลิก',
      bb:'บันทึก',
    },

     common: {
      loading: 'กำลังโหลด...',
      unknown: "ไม่ระบุ",
      email: 'อีเมล',
      viewAll: 'ดูทั้งหมด',
      viewNow: 'ดูเดี๋ยวนี้',
      error: 'เกิดข้อผิดพลาด',
      dayUnit: 'วัน',
      year: 'ปี',
      phone: 'เบอร์โทรศัพท์',
      license: 'ทะเบียน',
      startDate: 'วันที่เริ่มต้น',
      endDate: 'วันที่สิ้นสุด',
      total: 'ราคารวม',
      amount: 'จำนวนเงิน',
      approve: 'อนุมัติ',
      reject: 'ปฏิเสธ',
      cancel: 'ยกเลิก',
      back: 'กลับ',
      characterCount: 'อักขระ: {count}',
      close: 'ปิด',
      
      processing: 'กำลังดำเนินการ...',
      currency: (n: number) => `฿${n.toLocaleString()}`,
    },

    re:{
      s:'สำหรับผู้เช่ารถ',
      shops:'สำหรับเจ้าของร้าน',
      shopre:'ข้อมูลร้านค้า',
      a:'ลงทะเบียน',     
      b:'ข้อมูลร้านค้า',

    },
    customersearch:{
      no:'ไม่พบร้านเช่ารถที่ตรงกับเงื่อนไขการค้นหา',
      look:'ผลการค้นหา',
      search:'ค้นหารถเช่า',
      results:'ผลการค้นหา',
      title:'ค้นหาร้านเช่ารถ',
      car:'รถให้เช่า',
      vv:'ดูร้านเช่ารถ',
      ww:'สวัสดี',
      exit:'ออกจากระบบ',
      home:'หน้าแรก',
      rental:'การจองของฉัน',
      ready:'พร้อมเช่า',
      reserved:'ถูกจองแล้ว',
      maintain:'ซ่อมบำรุง',
      sub:'ค้นหารถเช่าหรือร้านเช่ารถ...',
      car2:'รถเช่า',
      car1:'ร้านเช่ารถ',
      type:'ประเภทรถ',
      tt:'ทั้งหมด',
      a:'รถเก๋ง',
      b:'รถ SUV',
      c:'รถแฮทช์แบ็ค',
      d:'รถกระบะ',
      e:'รถตู้',
      f:'รถหรู',
      g:'รถมอเตอร์ไซค์',
      price:'ราคาต่ำสุด',
      price2:'ราคาสูงสุด',
      gear:'เกียร์',
      g1:'ธรรมดา',
      g2:'อัตโนมัติ',
      fuel:'เชื้อเพลง',
      gasoline:'น้ำมันเบนซิน',
      diesel:'น้ำมันดีเซล',
      hybrid:'ไฮบริด',
      electric:'ไฟฟ้า',
      seats:'จำนวนที่นั่ง',
      seats1:'ที่นั่ง',
      ss:'ค้นหา',
      year:'ปี',
      shop:'ร้าน',
      g3:'เกียร์อัตโนมัติ',
      g4:'เกียร์ธรรมดา',
      day:'วัน',
      looks:'ดูรายละเอียด',
    },

    nayobuy:{
      title:'อ่านและยอมรับนโยบายก่อนทำการจอง',
      subtitle:'ข้าพเจ้าได้อ่านและยอมรับนโยบายทั้งหมดแล้ว',
      close:'ปิด',
      cc:'ยืนยันและทำการจอง',
    },
    

    record:{
      record:'ประวัติการเช่ารถ',
      re:'ตัวกรองข้อมูล',
      car:'จัดการและติดตามประวัติการเช่ารถทั้งหมด',
      search:'ค้นหา',
      tt:'ค้นหาด้วยชื่อลูกค้า,อีเมล,หรือป้ายทะเบียน',
      start:'วันที่เริ่มต้น',
      end:'วันที่สิ้นสุด',
      cc:'เรียงลำดับ',
      nd:'ใหม่ไปเก่า',
      mm:'เก่าไปใหม่',
      menu:'รายการเช่ารถ',
      total:'ทั้งหมด',
      ff:'รายการ',
      vv:'ข้อมูลรถ',
      xx:'ลูกค้า',
      zzz:'ระยะเวลา',
      aa:'สถานะการเช่า',
      ll:'สถานะการชำระ',
      jj:'ยอดรวม',
      w:'ถึง',
      a:'รอดำเนินการ',
      b:'กำลังเช่า',
      c:'กำลังคืนรถ',
      d:'คืนรถแล้ว',
      e:'เสร็จสิ้น',
      f:'ยกเลิก/มีปัญหา',
      g:'รอการชำระ/ตรวจ',
      h:'ชำระแล้ว',
      i:'คืนเงินแล้ว',
      j:'ชำระมีปัญหา',
      cv:'ไม่พบข้อมูล',
      dd:'ไม่มีประวัติการเช่ารถที่ตรงกับการค้นหา',
    },
    
    status: {
      pending: 'รออนุมัติ',
      confirmed: 'อนุมัติแล้ว',
      ongoing: 'กำลังเช่า',
      completed: 'เสร็จสิ้น',
      cancelled: 'ยกเลิก',
      available: 'ว่าง',
      rented: 'ถูกเช่า',
      hidden: 'ปิดให้บริการ',
      maintenance: 'ซ่อมบำรุง',
      unknown: 'ไม่ทราบสถานะ',
    },
    payStatus: {
      pending: 'รอชำระเงิน',
      pending_verification: 'รอยืนยันการชำระเงิน',
      paid: 'ชำระเงินแล้ว',
      rejected: 'การชำระเงินถูกปฏิเสธ',
      refunded: 'คืนเงินแล้ว',
    },
    auth: {
      pleaseLogin: 'กรุณาเข้าสู่ระบบ',
      notAuthenticated: 'ไม่ได้รับอนุญาต',
    },

    notifications: {
      title: 'การแจ้งเตือน',
      count: (n: number) => `${n} รายการ`,
      tabs: {
        all: 'ทั้งหมด',
        allTitle: 'แสดงการแจ้งเตือนทั้งหมด',
        pending: 'รออนุมัติ',
        pendingTitle: 'แสดงเฉพาะรายการที่รออนุมัติหรือรอการยืนยัน',
        returns: 'คำขอคืนรถ',
        cancelled: "ยกเลิก",
        return_requested: 'รออนุมัติคืนรถ',
        returnsTitle: 'แสดงคำขอคืนรถ',
      },
      dateTimeLabel: 'วันที่และเวลา',
      customer: 'ลูกค้า',
      email: 'อีเมล',
      type:'ยี่ห้อ',
      license:'ทะเบียนรถ',
      start:'วันเริ่มต้น',
      end:'วันสิ้นสุด',
      money:'ราคารวม',
      cf:'อนุมัติ',
      cc:'ปฎิเสธ',
      rentalPeriod: 'ระยะเวลาเช่า',
      paymentDate: 'วันที่ชำระเงิน',
      paymentMethod: 'วิธีการชำระเงิน',
      paymentStatus: 'สถานะการชำระเงิน',
      bookingInfo: 'ข้อมูลการจอง',
      paymentInfo: 'ข้อมูลการชำระเงิน',
      errorProcess: 'ไม่สามารถดำเนินการได้',
      errorAcknowledge: 'ไม่สามารถรับทราบการยกเลิก',
      errorFetch: 'ไม่สามารถดึงข้อมูลการแจ้งเตือน',
      proofOfPayment: 'หลักฐานการชำระเงิน',
      viewProof: 'ดูหลักฐาน',
      viewProofTitle: 'ดูหลักฐานการชำระเงิน',
      viewLarge: 'ดูภาพขนาดใหญ่',
      viewProofLargeAria: 'ดูหลักฐานการชำระเงินในขนาดใหญ่',
      successApprove: "ดำเนินการสำเร็จ!",
      successReject: "ดำเนินการเสร็จสิ้น (ปฏิเสธ)!",
      cancellationNote: "การจองนี้ถูกยกเลิกโดยลูกค้าแล้ว กรุณารับทราบเพื่อลบการแจ้งเตือน",
      cancellationDetails:"รายละเอียดการยกเลิก",
      cancellationDetailsDesc:"ตรวจสอบรายละเอียดการยกเลิกจากลูกค้า",
      returnNote:"หากอนุมัติการคืนรถ รถจะกลับไปเป็นสถานะพร้อมเช่า",
      reviewNote:"หากอนุมัติการจอง ลูกค้าจะเช่ารถได้ตามกำหนด หากปฏิเสธจะแจ้งลูกค้าว่าการจองถูกปฏิเสธ",
      acknowledge: "รับทราบ",
      cancelReason: "เหตุผลการยกเลิก",
      car: 'รถยนต์',
      review: 'ตรวจสอบ',
      reviewBooking: 'ตรวจสอบและอนุมัติการจอง',
      approveReturn: 'อนุมัติคืนรถ',
      returnRequest: 'ขอคืนรถ',
      modal: {
        returnTitle: 'อนุมัติการคืนรถ',
        reviewTitle: 'ตรวจสอบและอนุมัติการจอง',
        returnSubtitle: 'ตรวจสอบคำขอคืนรถจากลูกค้า',
        reviewSubtitle: 'ตรวจสอบรายละเอียดการจองและรายละเอียดการชำระเงิน',
      },
      returnHint: 'หากอนุมัติการคืนรถ รถจะกลับไปเป็นสถานะพร้อมเช่า หากปฏิเสธ รถยังคงเป็นสถานะกำลังเช่า',
      approvalHint: 'หากอนุมัติการจอง ลูกค้าจะสามารถเช่ารถได้ตามกำหนดการที่ระบุ หากปฏิเสธ ลูกค้าจะได้รับการแจ้งว่าการจองถูกปฏิเสธ',
      emptyTitle: 'ไม่มีการแจ้งเตือน',
      emptyDesc: 'ขณะนี้ไม่มีการแจ้งเตือนใดๆ',
    },

    booking:{
      title:'รายละเอียดการจอง',
      a:'การจองรถ',
      b:'สามารถยกเลิกได้ก่อนร้านจะทำการกดอนุมัติเท่านั้น',
      day:'วันที่จอง',
      tb:'ทะเบียน',
    },

    customerpay:{
      back:'กลับไปหน้ารายการจอง',
      title:'ชำระเงิน',
      sub:'การชำระเงินสำหรับการจองรถ',
      sub1:'กรุณาชำระเงินผ่านช่องทางที่ระบุด้านล่าง และอัปโหลดหลักฐานการชำระเงิน',
      date:'วันที่เริ่มต้น',
      end:'วันที่สิ้นสุด',
      number:'จำนวนวัน',
      day:'วัน',
      tt:'ยอดเงินที่ต้องชำระ',
      payment:'ชำระเงินผ่านพร้อมเพย์',
      qr:'คิวอาร์โค้ดพร้อมเพย์',
      scan:'สแกนเพื่อชำระเงินผ่านแอปธนาคาร',
      shop:'ร้าน',
      pp:'พร้อมเพย์',
      quantity:'จำนวนเงิน',
      copy:'คัดลอก',
      up:'อัปโหลดหลักฐานการชำระเงิน',
      click:'คลิกเพื่ออัปโหลดรูปภาพ',
      click1:'รองรับ PNG, JPG หรือ JPEG (สูงสุด 5MB)',
      cc:'ยกเลิก',
      cf:'ยืนยันการชำระเงิน',
      suggestions:'คำแนะนำ',
      a:'กรุณาโอนเงินไปยังหมายเลขพร้อมเพย์ตามที่ระบุให้ครบถ้วน',
      b:'ถ่ายรูปหลักฐานการโอนเงินที่มีรายละเอียดครบถ้วน เช่น วันเวลา จำนวนเงิน และรหัสอ้างอิง',
      c:'หลังจากอัพโหลดหลักฐานเรียบร้อย ร้านเช่ารถจะได้รับการแจ้งเตือนและตรวจสอบการชำระเงิน',
      d:'เมื่อได้รับการยืนยันแล้ว คุณจะได้รับการแจ้งเตือนผ่านอีเมลและสามารถดูสถานะการจองได้ในหน้าการจองของฉัน',
    },

    carTypes: {
      sedan: 'รถเก๋ง',
      suv: 'รถ SUV',
      hatchback: 'รถแฮทช์แบ็ค',
      pickup: 'รถกระบะ',
      van: 'รถตู้',
      luxury: 'รถหรู',
    },
    actions: {
      addCar: 'เพิ่มรถใหม่',
      addFirstCar: 'เพิ่มรถคันแรก',
      manageBlacklist: 'จัดการบัญชีดำ',
      editCar: 'แก้ไขข้อมูลรถยนต์',
      editCarAria: 'แก้ไขข้อมูลรถยนต์นี้',
      edit: 'แก้ไข',
      addImage: 'เพิ่มรูปภาพ',
      addImageAria: 'เพิ่มรูปภาพของรถยนต์นี้',
      manageStatus: 'จัดการสถานะ',
      manageStatusAria: 'จัดการสถานะของรถยนต์นี้',
      
    },
    shopDashboard: {
      title: 'หน้าหลัก',
      welcome: 'ยินดีต้อนรับ',
      popularTitle: 'แดชบอร์ด',
      goPopularAria: 'ไปหน้ารถที่นิยม',
      yourCars: 'รถยนต์ของคุณ',
      itemsCount: (n: number) => `แสดง ${n} รายการ`,
      noCars: 'คุณยังไม่มีรถยนต์ในระบบ',
      pendingNotifications: (n: number) => `คุณมี ${n} การแจ้งเตือนที่รอดำเนินการ`,
    },
    reviewmodal:{
      write:'เขียนรีวิว',
      shop:'ชื่อร้าน',
      date:'วันที่เช่า',
      score:'คะแนน',
      star:'ดาว',
      comment:'ความคิดเห็น (ไม่บังคับ)',
      title:'แบ่งปันประสบการณ์การใช้รถคันนี้...',
      a:'1000 ตัวอักษร',
      cc:'ยกเลิก',
      sent:'ส่งการรีวิว',
    },

    shoppage:{
      back:'ย้อนกลับ',
      tel:'โทร',
      car:'รถยนต์ทั้งหมดจากร้าน',
      year:'ปี',
      seats:'ที่นั่ง',
      day:'วัน',
      look:'ดูรายละเอียดและการจอง',
    },

    pending:{
      a:'รอดำเนินการ',
      b:'กำลังเช่า',
      c:'กำลังคืนรถ',
      d:'คืนรถแล้ว',
      e:'เสร็จสิ้น',
      f:'ยกเลิก/มีปัญหา',
      g:'รอการชำระ/ตรวจ',
      h: 'ชำระแล้ว',
      i:'คืนเงินแล้ว',
      j:'ชำระมีปัญหา'
    },

    Review:{
    title: "รีวิวและประเมิน",
    subtitle: "จัดการรีวิวของคุณและเขียนรีวิวใหม่",
    header: "รอรีวิว",
    me:"รีวิวของฉัน",
    titles:"ไม่มีการเช่าที่รอรีวิว",
    Subtitles:"เมื่อคุณเช่ารถและใช้งานเสร็จแล้ว จะสามารถเขียนรีวิวได้ที่นี่",
    date:"รีวิวเมื่อ",
    addCar: 'เพิ่มรถใหม่',
    manageBlacklist: 'จัดการบัญชีดำ',
    managepolicy:'จัดการนโยบาย',
    },

    Booking: {
      title: "การจองรถของฉัน",
      subtitle: "จัดการการจองรถยนต์ของคุณ",
      total:"รวมทั้งหมด",
      date:"วันที่เช่า",
      statuspay:"สถานะการชำระเงิน",
      license: "ป้ายทะเบียน",
      lo:"สถานที่รับรถ",
      lo2:"สถานที่คืนรถ",
      p:"สามารถยกเลิกได้",
      year:"ปี",
      tabs: {
        all: "ทั้งหมด",
        pending: "รออนุมัติ",
        active: "ใช้งานอยู่",
        history: "ประวัติ",
      },
      loading: "กำลังโหลดข้อมูล...",
      emptyTitle: "ไม่พบรายการจอง",
      emptySubtitle: "เริ่มต้นการจองรถยนต์ของคุณได้เลย",
      emptyButton: "เลือกดูรถเช่าเพิ่มเติม",

      status: {
        pending: "รออนุมัติ",
        confirmed: "ยืนยันแล้ว",
        ongoing: "กำลังใช้งาน",
        return_requested: "ขอคืนรถ",
        return_approved: "คืนรถแล้ว",
        completed: "เสร็จสิ้น",
        cancelled: "ยกเลิกแล้ว",
      },

      paymentStatus: {
        pending_verification: "รอตรวจสอบ",
        paid: "ชำระเงินแล้ว",
        refunded: "คืนเงินแล้ว",
        refund_pending: "รอการคืนเงิน",
        failed: "การชำระเงินล้มเหลว",
      },

      buttons: {
        viewCar: "ดูรายละเอียดรถ",
        pay: "ชำระเงิน",
        requestReturn: "ขอคืนรถ",
        review: "เขียนรีวิว",
        cancelBooking: "ยกเลิกการจอง",
      },

      cancelModal: {
        title: "ยืนยันการยกเลิกการจอง",
        message:
          "คุณแน่ใจหรือไม่ที่ต้องการยกเลิกการจองนี้? หากยกเลิกแล้วรถคันนี้จะกลับไปเป็นสถานะพร้อมเช่าและการกระทำนี้ไม่สามารถย้อนกลับได้",
        cancel: "ยกเลิก",
        confirm: "ยืนยันการยกเลิก",
        confirming: "กำลังยกเลิก...",
      },

      returnModal: {
        title: "ยืนยันการขอคืนรถ",
        message:
          "โปรดตรวจสอบให้แน่ใจก่อนกดยืนยัน การคืนรถจะถือว่าสำเร็จต่อเมื่อคุณได้นำรถมาคืนที่หน้าร้าน และได้รับเงินค่าประกันคืนครบถ้วนเรียบร้อยแล้วเท่านั้น หากรถยังไม่ถูกส่งคืนหรือยังไม่ได้รับเงินค่าประกัน กรุณาอย่ากดยืนยัน เพื่อป้องกันการสูญเสียสิทธิ์ในการรับเงินคืน",
        cancel: "ยกเลิก",
        confirm: "ยืนยันขอคืนรถ",
        confirming: "กำลังส่งคำขอ...",
      },
    },

    reviewcustomer:{
      reviewcus:'รีวิวจากลูกค้า',
      review:'รีวิว',
      no:'ยังไม่มีรีวิวสำหรับรถคันนี้',
      frist:'เป็นคนแรกที่รีวิวรถคันนี้',
    },

    CustomerDashboard: {
      customername:"ชื่อผู้ใช้",
      love:'หากท่านประสงค์จะขอรับเงินคืน กรุณาติดต่อร้านเช่าทันทีหลังจากทำการยกเลิกการจอง การยกเลิกจะถือว่าเสร็จสมบูรณ์ก็ต่อเมื่อท่านได้รับเงินคืนเรียบร้อยแล้ว ทั้งนี้ ท่านสามารถยืนยันการยกเลิกได้เฉพาะก่อนที่ร้านเช่าจะกดอนุมัติการจองเท่านั้น กรุณาตรวจสอบข้อมูลให้ครบถ้วนก่อนกดยืนยัน',
      title: "ระบบเช่ารถ",
      aa:'จองรถสำเร็จ!',
      subtitle:'รายละเอียดการจอง',
      ssubtitle:'การจองรถ',
      day:'วันที่จอง',
      day2:'จำนวนวัน',
      ta:'ทะเบียน',
      shop:'ชื่อร้าน',
      oo:'สามารถยกเลิกได้ก่อนร้านจะทำการกดอนุมัติเท่านั้น',
      dd:'ข้อมูลร้านเช่า',
      ww:'วัน',
      sta:'สถานะการชำระ',
      saru:'สรุปค่าใช้จ่าย',
      total:'ค่าเช่ารถ',
      b:'บาท',
      wan:'วัน',
      ru:'ราคารวมทั้งสิ้น',
      i:'กลับไปหน้าการจอง',
      cc:'ยกเลิกการจอง',
      ccc:'ยืนยันการยกเลิกการจอง',

      bb:'กำลังนำคุณไปยังหน้าชำระเงิน...',
      carDetails: 'รายละเอียดรถ',
      titles:'รถคันนี้ถูกจองแล้ว',
      subtitles:'กรุณาเลือกรถคันอื่นหรือลองใหม่ในภายหลัง',
      color: 'สี',
      type: 'ประเภท',
      seats: 'ที่นั่ง',
      start:"วันที่เริ่มต้น",
      end:"วันที่สิ้นสุด",

      transmission: {
        auto: 'อัตโนมัติ',
        manual: 'ธรรมดา',
      },
      fuel: {
        label: 'เชื้อเพลิง',
        gasoline: 'น้ำมันเบนซิน',
        diesel: 'น้ำมันดีเซล',
        hybrid: 'ไฮบริด',
        electric: 'ไฟฟ้า',
      },
      gear:"เกียร์",
      f:"เชื้อเพลิง",
      details:"รายละเอียด",
      tel:"เบอร์โทรศัพท์",
      address:"ที่อยู่",
      pp:"หมายเลขพร้อมเพย์",
      look:"ดูรถอื่นๆ จากร้านนี้",
      
      welcome: "สวัสดี !! ค้นหารถที่ใช่สำหรับคุณ",
      searchPlaceholder: "ค้นหารถยนต์, ยี่ห้อ, หรือร้านค้า...",
      searchButton: "ค้นหา",
      clearSearch: "ล้างการค้นหา",
      advancedSearch: "ค้นหาขั้นสูง →",
      availableCars: "รถยนต์พร้อมจอง",
      searchResults: 'ผลการค้นหา "{searchTerm}"',
      noCarsFound: "ไม่พบรถยนต์ที่คุณค้นหา",
      noCarsAvailable: "ไม่มีรถยนต์พร้อมจอง",
      noCarsAvailableMessage: "ขณะนี้ยังไม่มีรถยนต์ที่พร้อมให้เช่า",
      viewAllCars: "ดูรถยนต์ทั้งหมด",
      recentBookings: "การจองล่าสุด",
      viewAllBookings: "ดูทั้งหมด →",
      pendingReviews: "รอรีวิว",
      pendingReviewsMessage: "การเช่าที่รอรีวิว",
      locationone:"สถานที่รับรถ",
      location:"สถานที่คืนรถ",
      writeReview: "เขียนรีวิว",
      bookings: "การจองของฉัน",
      reviews: "รีวิว",
      profile: "โปรไฟล์",
      Ready: "พร้อมให้เช่า",
      Reserve:"จองรถคันนี้",
      Insurance: "ค่าประกัน",
      Insuranceone: "จ่ายครั้งเดียว",
      logout: "ออกจากระบบ",
      themeToggle: "เปลี่ยนธีม (ปัจจุบัน: {theme})",
      footer: "© 2025 ระบบเช่ารถ. สร้างด้วย Next.js และ Node.js",
      footerMessage: "บริการเช่ารถยนต์ที่ดีที่สุดสำหรับคุณ",
      frist:"หน้าแรก",
      back:"ย้อนกลับ",
      Notifications:"การแจ้งเตือน",
      rentalStatus: {
        approved: "อนุมัติแล้ว",
        confirmed: "ยืนยันแล้ว",
        pending: "รออนุมัติ",
        ongoing: "กำลังเช่า",
        completed: "เสร็จสิ้น",
        cancelled: "ยกเลิก",
        save:"บันทึก",
      
      },
      totalAmount: "รวมทั้งหมด",
      shopLabel: "ร้าน: {shopName}",
      dateRange: "{startDate} - {endDate}",
      pricePerDay: "/วัน",
      viewDetails: "ดูรายละเอียด",
      price:"ราคา",
      thb:"บาท",
      loading: "กำลังโหลดรถยนต์..."
    }
    
  },
  en: {
    LanguageSwitcher: {
      thai: "Thai",
      english: "English"
    },

    

    Login: {
      sub:'Login failed. Please check your username and password.',
      title: "Log in",
      email:"Email",
      username: "Username",
      password: "Password",
      confirmpassword: "Confirm Password",
      role: "Role",
      Phone:"Phone",
      Chooserole: "ChooseRole",
      customer: "Customer",
      shop: "Shop",
      Reservewhen:"Reserve when",
      address:"Address",
      shopname: "ShopName",
      promptpay: "Prompt Pay ID",
      rememberMe: "RememberMe",
      forgotPassword: "Forgot password?",
      submit: "Log in",
      submitting: "Processing...",
      noAccount: "Don't have an account?",
      haveAccount: "have an account ?",
      register: "Register",
      error:"Please fill in completely.",
      successRegistered: "Registered successfully, please log in",
      loginFailedGeneric: "Login failed. Please check your username and password",
      errorDuringLogin: "An error occurred during login",
      validation: {
        usernameRequired: "Please enter your username",
        passwordRequired: "Please enter your password",
      }
    },

    Review: {
    title: "Reviews and Ratings",
    subtitle: "Manage your reviews and write new reviews",
    header: "Waiting for reviews",
    me: "My reviews",
    titles:"No rentals pending review",
    Subtitles:"Once you've rented a car and finished using it, you can leave a review here.",
    date:"Reviewed on",
    addCar: 'Add car',
    manageBlacklist: 'Manage blacklist',
    managepolicy:'manage policy',
    },

    popular:{
  exit:'Return to home page',
  summary: 'Income Summary',
  income: 'Daily Income',
  total: 'Total Income',
  rental: 'All Rentals',
  money: 'Monthly Income Trend (Past 12 Months)',
  revenue: 'Income',
  top: 'Top 5 Most Popular Cars (by Number of Rentals)',
  all: 'All Car Rankings',
  rating: 'Ranking',
  license: 'License Plate',
  type: 'Type',
  gear: 'Gear',
  seat: 'Seats',
  status:'Status',
  available: 'Available',
  noavai: 'Not Available',
  Renting: 'Currently Renting',
  day: 'Per Day',
  time: 'Times',
  review: 'Reviews',
  sum: 'Popular Car Statistics Summary',
  tr: 'Total Rental Times',
  score: 'Total Average Rating',
  reviewt: 'All Reviews',
  yu: 'Average Price/Day',
  vv:'number of times rented',
  },

    blaklist:{
    title: 'Suspended User List Management System',
    other: "Other (please specify)",
    pleaseFillOther: "Please fill the reason in 'Other'.",
    subtitle: 'Manage and Control User Access',
    emai: 'Search by Username or Email',
    search: 'Search',
    label: 'Select Reason for Suspension',
    a: 'Unauthorized Vehicle Modification',
    b: 'Delayed Vehicle Return',
    c: 'Misuse of Vehicle',
    d: 'Retroactive Ticket',
    e: 'Other (Please Specify)',
    f:'Please provide a reason',
    listname: 'Suspended User List',
    list: 'List',
    no: 'No Users on the Suspended List',
    notitle: 'All Users Can Access Normally',
    results: 'Search Results',
    add: 'Add to Suspend List',
    cancel: 'Cancel Suspend',
    date: 'Date Added',
    reason: 'Reason',

    },

    Policy: {
      title: 'Manage Store Policies',
      subtitle: 'Add/Edit/Delete policies to display to customers on your storefront',
      loading: 'Loading policies...',
      editTitle: 'Edit policies',
      createTitle: 'Create policies',
      previewTitle: 'Policy preview',
      noPolicy: 'No policies yet. Please click "Edit" to create one',
      noPolicyText: 'No text yet',
      labels: {
        policyText: 'Policy text (to be displayed to users)',
        preview: 'Preview that customers will see',
      },
      buttons: {
      edit: 'Edit',
      create: 'Create policy',
      delete: 'Delete policy',
      deleting: 'Deleting...',
      save: 'Save policy',
      saving: 'Saving...',
      showPreview: 'Show preview',
      hidePreview: 'Hide preview',
      },
      errors: {
      fetchFailed: 'Failed to load policy',
      emptyPolicy: 'Please enter policy text',
      saveFailed: 'Failed to save policy',
      deleteFailed: 'Failed to delete policy',
      },
      success: {
      created: 'Policy created successfully',
      updated: 'Successfully edited policy',
      deleted: 'Policy deleted successfully',
      },
      deleteConfirm: {
      title: 'Confirm policy deletion',
      message: 'Once deleted, customers will no longer see the policy on your storefront. Do you want to continue?',
      },
      },

    

    Home: {
      title: "Welcome",
      image:'Manage images',
      submit: "Login",
      submittwo: "Register",
      head: "Car rental service convenient",
      Dashboard:"Dashboard",
    },

      Addcar: {
      brand:'brand',
      title: 'Add new car',
      model: 'Model',
      year: 'Year',
      Carregistration: 'Vehicle registration',
      type: 'Vehicle type',
      gear: 'Gear',
      fuel: 'Fuel',
      seats: 'Number of seats',
      color: 'Color',
      price: 'Rental price per day (baht)',
      Insurance : 'Insurance price (baht)',
      details: 'More details',
      cancel:'cancel',
      AddCar:'Add car', 
      Sedan: 'Sedan',
      SUV: 'SUV',
      hatchback: 'Hatchback',
      pickup: 'Pickup truck',
      van: 'Van',
      luxury: 'Luxury car',
      motorbike: 'Motorcycle',
      automatic:'Automatic',
      manual:'Manual',
      gasoline:'gasoline',
      diesel:'diese',
      hybrid:'hybrid',
      electric:'electric',
      seat:'seat',
      money:'0 (optional)',
      },

      editcar: {
    brand: 'Brand',
    title: 'Edit Car Information',
    model: 'Model',
    year: 'Year',
    car: 'Vehicle Registration',
    type: 'Vehicle Type',
    gear: 'Gear',
    fuel: 'Fuel',
    seats: 'Number of Seats',
    color: 'Color',
    price: 'Rental Price per Day (Baht)',
    details: 'Additional Details',
    cancel: 'Cancel',
    AddCar: 'Save Changes',
    Sedan: 'Sedan',
    SUV: 'SUV',
    hatchback: 'Hatchback',
    pickup: 'Pickup Truck',
    van: 'Van',
    luxury: 'Luxury Car',
    motorbike: 'Motorcycle',
    automatic: 'Automatic',
    manual: 'Manual',
    gasoline: 'Gasoline',
    diesel: 'Diesel',
    hybrid: 'Hybrid',
    electric: 'Electric',
    t:'Status',
    status: 'Available',
    sstatus: 'Rented',
    ssstatus:'Under maintenance',
    sssstatus:'Service closed',
    },

  editimages:{
  edit: 'Manage images',
  new: 'Upload new images',
  click: 'Click to select a file',
  a: 'PNG, JPG, WEBP, size up to 5MB',
  b: 'Done',
  },
  

  carsatana:{
  car:'Manage car status',
  a:'Select the status you want to change',
  status:'Available',
  sstatus:'Rented',
  ssstatus:'Under maintenance',
  sssstatus:'Service closed',
  cc:'Cancel',
  pp:'Change status',
  },

    profile:{
    title: "My Profile",
    subtitle: "Manage your personal information and view usage statistics",
    header: "Personal Information",
    date: "Member Since",
    edit:"Edit",
    statistics:"Statistics",
    
    all:"All bookings",
      
    use:"in use",
      
    finish:"finish",
    ff:' Update this profile',

    },

    shopprofile:{
    title: "Shop Profile",
    subtitle: "Manage Your Personal Information and Shop",
    edit: "Edit Information",
    header: "Username",
    subheader: "Shop Name",
    pp: "PromptPay Number",
    tel: "Phone Number",
    address: "Address",
    date: "Membership Date",
    email: "Email",
    shop: "Role",
    ee: "Shop",
    back: "Back",
    ff: "Profile Updated Successfully",
    cc:'Cancel',
    bb:'Save',  
    },

     common: {
      loading: 'Loading...',
      viewAll: 'View all',
      viewNow: 'View now',
      error: 'Error',
      dayUnit: 'day',
      unknown: "not specified",
      year: 'Year',
      license: 'License',
      email: 'Email',
      back: 'back',
      characterCount: 'characters: {count}',
      phone: 'Phone',
      startDate: 'Start date',
      endDate: 'End date',
      total: 'Total',
      amount: 'Amount',
      approve: 'Approve',
      reject: 'Reject',
      cancel: 'Cancel',
      close: 'Close',
      processing: 'Processing...',
      currency: (n: number) => `$${n.toLocaleString()}`, // ปรับสกุลเงินตามต้องการ
    },

    re:{
      s: 'For car rentals',
      shops: 'For shop owners',
      shopre: 'Store information',
	    a:'Register',
      b:'Store information',
    },

    customersearch:{
      look:'search results',
      no:'No car rental shops found that match the search criteria',
      search:'Search for a car rental',
      results: 'Search Results',
      vv:'Look at the car rental shop',
      home: 'Home',
      title: 'Find a car rental',
      car: 'Car for rent',
      ww:'Hello',
      exit:'Log out',
      rental: 'My Bookings',
      ready: 'Ready to Rent',
      reserved: 'Already Reserved',
      maintain: 'Maintenance',
      sub:'Search for a car rental or car rental shop...',
      car2:'Car rental',
      car1:'Car rental shop',
      type:'Car type',
      tt:'All',
      a:'Sedan',
      b:'SUV',
      c:'Hatchback',
      d:'Pickup truck',
      e:'Van',
      f:'Luxury car',
      g:'Motorcycle',
      price:'Lowest price',
      price2:'Highest price',
      gear:'Gear',
      g1:'Manual',
      g2:'Automatic',
      fuel:'Fuel',
      gasoline:'Gasoline',
      diesel:'Diesel',
      hybrid:'Hybrid',
      electric:'Electric',
      seats:'Number of seats',
      seats1:'seats',
      ss:'Search',
      year:'Year',
      shop:'Shop',
      g3:'Automatic transmission',
      g4:'Manual transmission',
      day:'day',
      looks:'view details',
      },

      nayobuy:{
      title: 'Read and accept the policies before booking',
      subtitle: 'I have read and agree to all policies',
      close: 'Close',
      cc: 'Confirm and make a booking',
      },
    

    record:{
    record:'Car Rental History',
    re:'Data filter',
    car:'Manage and track your entire car rental history',
    search:'Search',
    tt:'Search by customer name, email, or license plate',
    start:'Start Date',
    end:'End Date',
    cc:'Sort',
    nd:'New to Old',
    mm:'Old to New',
    menu:'Car Rental List',
    total:'All',
    ff:'List',
    vv:'Car Information',
    xx:'Customer',
    zzz:'Duration',
    aa:'Rental Status',
    ll:'Payment Status',
    jj:'Total',
    w:'To',
    a:'Pending',
    b:'Renting',
    c:'Car Returning',
    d:'Car Returned',
    e:'Completed',
    f:'Cancelled/Problem',
    g:'Awaiting Payment/Review',
    h:'Paid',
    i:'Refunded',
    j:'Payment problem',
    cv:'No data found',
    dd:'No car rental history matching the search',
    },

    status: {
      pending: 'Pending',
      confirmed: 'Confirmed',
      ongoing: 'Ongoing',
      completed: 'Completed',
      cancelled: 'Cancelled',
      available: 'Available',
      rented: 'Rented',
      hidden: 'hidden',
      maintenance: 'Maintenance',
      unknown: 'Unknown',
    },

    payStatus: {
      pending: 'Payment pending',
      pending_verification: 'Awaiting verification',
      paid: 'Paid',
      rejected: 'Payment rejected',
      refunded: 'Refunded',
    },

    auth: {
    pleaseLogin: 'Please log in',
    notAuthenticated: 'Not Authorized',
    
    },
    notifications: {
      title: 'Notifications',
      count: (n: number) => `${n} items`,
      tabs: {
        all: 'All',
        allTitle: 'Show all notifications',
        pending: 'Pending',
        return_requested: 'return requested',
        pendingTitle: 'Show only pending/awaiting verification',
        returns: 'Return requests',
        cancelled: "cancelled",
        returnsTitle: 'Show return requests',
      },
       dateTimeLabel: 'Date & time',
      customer: 'Customer',
      email: 'email',
      type: 'brand',
      license: 'vehicle registration',
      start: 'start date',
      end: 'end date',
      money: 'total price',
      cf: 'approved',
      cc: 'rejected',
      rentalPeriod: 'Rental period',
      paymentDatepaymentDate: 'Payment date',
      paymentMethod: 'Payment method',
      paymentStatus: 'Payment status',
      bookingInfo: 'Booking details',
      paymentInfo: 'Payment details',
      proofOfPayment: 'Proof of payment',
      viewProof: 'View proof',
      viewProofTitle: 'View payment proof',
      viewLarge: 'View large',
      viewProofLargeAria: 'View payment proof in large size',
      cancellationNote: "This booking has been cancelled by the customer. Please acknowledge it to delete the notification.",
      successApprove: "Process completed successfully!",
      cancellationDetails:"Cancellation details",
      cancellationDetailsDesc:"Check cancellation details from customers.",
      successReject: "Process completed (rejected)!",
      acknowledge: "Acknowledged",
      cancelReason: "Reason for canceling",
      errorFetch: 'Unable to fetch notification data',
      errorProcess: 'Unable to complete the operation',
      errorAcknowledge: 'Unable to acknowledge cancellation',
      returnNote: "If the return is approved, the vehicle will return to the rental status.",
      reviewNote: "If the reservation is approved, the customer will be able to rent the vehicle as scheduled. If the reservation is rejected, the customer will be notified that the reservation has been declined.",
      car: 'Car',
      review: 'Review',
      reviewBooking: 'Review & approve booking',
      approveReturn: 'Approve return',
      returnRequest: 'Return request',
      modal: {
        returnTitle: 'Approve return',
        reviewTitle: 'Review & approve booking',
        returnSubtitle: 'Review the customer’s return request',
        reviewSubtitle: 'Review booking and payment details',
      },
      returnHint: 'If approved, the car becomes available. If rejected, it remains rented.',
      approvalHint: 'If approved, the customer can rent as scheduled. If rejected, the customer will be notified.',
      emptyTitle: 'No notifications',
      emptyDesc: 'There are no notifications at the moment.',
    },

    customerpay:{
    back:'Back to the booking page',
    title:'Payment',
    sub:'Payment for car booking',
    sub1:'Please pay via the channels specified below. and upload proof of payment',
    date: 'Start date',
    end: 'End date',
    number: 'Number of days',
    day: 'Days',
    tt: 'Amount to be paid',
    payment: 'Pay via PromptPay',
    qr: 'PromptPay QR Code',
    scan: 'Scan to pay via bank app',
    shop: 'Shop',
    pp: 'PromptPay',
    quantity: 'Amount',
    up:'Upload proof of payment',
    copy: 'Copy',
    click: 'Click to upload image',
    click1: 'Supports PNG, JPG, or JPEG (maximum 5MB)',
    cc: 'Cancel',
    cf: 'Confirm payment',
    suggestions: 'Recommendations',
    a: 'Please transfer money to the specified PromptPay number completely',
    b: 'Take a photo of the proof of transfer with complete details such as date, time, amount, and reference code',
    c: 'After uploading proof, the car rental shop will receive a notification and verify the payment',
    d: 'Once confirmed You will receive an email notification and can view your booking status on the My Bookings page.',
    },

    carTypes: {
      sedan: 'Sedan',
      suv: 'SUV',
      hatchback: 'Hatchback',
      pickup: 'Pickup',
      van: 'Van',
      luxury: 'Luxury',
    },
    actions: {
      addCar: 'Add car',
      addFirstCar: 'Add first car',
      manageBlacklist: 'Manage blacklist',
      editCar: 'Edit car',
      editCarAria: 'Edit this car',
      edit: 'Edit',
      addImage: 'Add image',
      addImageAria: 'Add image for this car',
      manageStatus: 'Manage status',
      manageStatusAria: 'Manage this car status',
      
    },
    shopDashboard: {
      title: 'HOME',
      welcome: 'Welcome',
      popularTitle: 'Dashboard',
      goPopularAria: 'Go to popular cars',
      yourCars: 'Your cars',
      itemsCount: (n: number) => `Showing ${n} items`,
      noCars: 'You have no cars yet',
      pendingNotifications: (n: number) => `You have ${n} pending notifications`,
    },
    reviewmodal:{
      write:'Write a review',
      shop: 'Shop Name',
      date: 'Rental Date',
      score: 'Score',
      star: 'Stars',
      comment: 'Comment (optional)',
      title: 'Share your experience using this car...',
      a: '1000 Characters',
      cc: 'Cancel',
      sent: 'Submit Review',
      },

      shoppage:{
      back: 'Back',
      tel: 'Call',
      car: 'All cars from the shop',
      year: 'Year',
      seats: 'Seats',
      day: 'Day',
      look: 'View details and reservations',
      },
      
     pending: {
      a: 'Pending',
      b: 'Renting',
      c: 'Car being returned',
      d: 'Car returned',
      e: 'Completed',
      f: 'Cancelled/Problem',
      g: 'Awaiting payment/verification',
      h: 'Paid',
      i: 'Refunded',
      j: 'Problem with payment'
      },

    Booking: {
      title: "My Car Bookings",
      subtitle: "Manage your car rental reservations",
      total: "Total",
      date: "Rental Date",
      statuspay: "Payment Status",
      license: "License Plate",
      lo:"Pickup Location",
      lo2:"Return Location",
      p:"Can be canceled",
      year:"year",
    
      tabs: {
        all: "All",
        pending: "Pending Approval",
        active: "Active",
        history: "History",
      },
      loading: "Loading data...",
      emptyTitle: "No bookings found",
      emptySubtitle: "Start your car rental journey now",
      emptyButton: "Browse more cars",

      status: {
        pending: "Pending",
        confirmed: "Confirmed",
        ongoing: "Ongoing",
        return_requested: "Return Requested",
        return_approved: "Returned",
        completed: "Completed",
        cancelled: "Cancelled",
      },

      paymentStatus: {
        pending_verification: "Pending Verification",
        paid: "Paid",
        refunded: "Refunded",
        refund_pending: "Refund Pending",
        failed: "Payment Failed",
      },

      buttons: {
        viewCar: "View Car Details",
        pay: "Make Payment",
        requestReturn: "Request Return",
        review: "Write Review",
        cancelBooking: "Cancel Booking",
      },

      cancelModal: {
        title: "Confirm Cancellation",
        message:
          "Are you sure you want to cancel this booking? Once cancelled, the car will be available for others to rent and this action cannot be undone.",
        cancel: "Cancel",
        confirm: "Confirm Cancellation",
        confirming: "Cancelling...",
      },

      returnModal: {
        title: "Confirm Return Request",
        message:
          "Please ensure you have already returned the car to the shop and received your deposit refund before confirming. If not, do not confirm yet to avoid losing your refund rights.",
        cancel: "Cancel",
        confirm: "Confirm Return",
        confirming: "Sending request...",
      },
    },
    reviewcustomer:{
    reviewcus:'Customer Review',
    review:'Review',
    no:'There are no reviews for this car yet.',
    frist:'Be the first to review this car.',
    },
    

    CustomerDashboard: {
      customername:"Username",
      title: "Car Rental System",
      love:'If you wish to request a refund, please contact the rental shop immediately after canceling your reservation. The cancellation will be considered complete once you have received your refund. You can only confirm your cancellation before the rental shop approves your reservation. Please check all information carefully before confirming.',
      aa:'Car reservation completed!',
      bb:'You are being redirected to the payment page...',
      titles: 'Because this is already reserved',
      subtitles: 'Is there something else or try again?',
      subtitle: 'Booking Details',
      ssubtitle: 'Vehicle Booking',
      ccc:'Confirm booking cancellation',
      day: 'Booking Date',
      day2: 'Number of Days',
      ta: 'Registration',
      shop:'Shop Name',
      oo:'Cancellation is allowed only before the shop approves it.',
      dd:'Rental Shop Information',
      ww:'Day',
      sta:'Payment Status',
      saru:'Total Expenses',
      total:'Car Rental',
      b:'Baht',
      wan:'Day',
      ru:'Total Price',
      i:'Return to Booking Page',
      cc:'Cancel Booking',
      gear: "gear",
      f: "fuel",
      details: "details",
      tel: "phone number",
      address: "address",
      pp: "PromptPay number",
      look: "See other cars from this shop",
      welcome: "Hello!! Find the right car for you.",
      searchPlaceholder: "Search for cars, brands, or shops...",
      searchButton: "Search",
      clearSearch: "Clear Search",
      advancedSearch: "Advanced Search →",
      availableCars: "Available Cars",
      searchResults: 'Search Results for "{searchTerm}"',
      noCarsFound: "No cars found for your search",
      noCarsAvailable: "No Cars Available",
      noCarsAvailableMessage: "There are currently no cars available for rent",
      viewAllCars: "View All Cars",
      recentBookings: "Recent Bookings",
      viewAllBookings: "View All →",
      pendingReviews: "Pending Reviews",
      pendingReviewsMessage: "Rentals awaiting review",
      writeReview: "Write Review",
      bookings: "My Bookings",
      reviews: "Reviews",
      profile: "Profile",
      Notifications:"Notifications",
      Ready: "Ready",
      carDetails: 'Car Details',
      color: 'Color',
      type: 'Type',
      Reserve:"Reserve this car",
      seats: 'Seats',
      start: "Start Date",
      Insuranceone: "One time payment",
      end: "End Date",
      locationone:"Car pick-up location",
      location:"car return location",
      transmission: {
        auto: 'Automatic',
        manual: 'Manual',
      },
      fuel: {
        label: 'Fuel Type',
        gasoline: 'Gasoline',
        diesel: 'Diesel',
        hybrid: 'Hybrid',
        electric: 'Electric',
      },
      
      
      Insurance: "Insurance cost",
      logout: "Log Out",
      themeToggle: "Toggle Theme (current: {theme})",
      footer: "© 2025 Car Rental System. Built with Next.js and Node.js",
      footerMessage: "The best car rental service for you",
      frist:"Home",
      back:"retrospective",
      rentalStatus: {
        approved: "Approved",
        confirmed: "Confirmed",
        pending: "Pending",
        ongoing: "Ongoing",
        completed: "Completed",
        cancelled: "Cancelled",
        save:"record",
        
      
      },
      totalAmount: "Total Amount",
      shopLabel: "Shop: {shopName}",
      dateRange: "{startDate} - {endDate}",
      pricePerDay: "/day",
      viewDetails: "View Details",
      loading: "Loading cars...",
      price:"price",
      thb:"THB",
    }
  }
};
